### ISSUE TITLE
if all spaces were cleared after scoring the board, it is the same as getting another joker/joker bonus

### ISSUE THREAD

**Issue by AntoineTurmel** [mikekeith52/LockNRoll#3]
It's not a rule from the official game ? https://armorgames.com/play/4283/lock-n-roll

![image](https://user-images.githubusercontent.com/119288/172070776-a1a5b937-c5a0-473f-9ddb-97e447054329.png)
The bonus gauge made me have a second joker, but then no +1000 bonus points.

**Comment by AntoineTurmel** [comment]
You have to clear 16 dices ? it's not just all board is cleared ?
![Animation12](https://user-images.githubusercontent.com/119288/172072319-131f1775-8396-43b3-b892-ec3a355d59af.gif)

**Comment by mikekeith52** [comment]
Thank you for raising the issue. There are several versions of the game floating around and the one I am most familiar treats any board clear the same as earning a joker, giving a bonus (that starts at 1,000 initially but increases each time it is earned) if two jokers are already obtained. The gif you shared does not look like it does the same and the rules in the readme also don't state this rule. I programmed the bonus based on my own familiarity with the version I play on my phone, which appears to have this difference. 

As such, there are two potential fixes:

1) Update the readme to let users know this bonus is also programmed into the game
2) Update the game source code so that this bonus no longer counts

As you are the only person I am aware of who uses this program, do you have a preference on which of these two options to pursue?

**Comment by AntoineTurmel** [comment]
I think you just have to update the readme.
In fact I'm working on my own implementation of the game in Lua, I started off without any hints on how to code the game, but I figured out I could look on how others handle scoring and line checking. Your code is helpful :)

**Comment by mikekeith52** [comment]
Great! Updated the readme with that additional clarification. I'm glad you find the code helpful!
